name             'code_generator'
maintainer       'Jacob McCann'
maintainer_email 'jmccann.git@gmail.com'
license          'Apache 2 License'
description      'Generates Chef code for Chef DK'
long_description 'Generates Chef code for Chef DK'
version          '0.1.0'
